name: Deploy Preview

on:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 22
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus
        run: npm run build

      - name: Vercel login
        run: vercel login ${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel Preview
        run: vercel --token ${{ secrets.VERCEL_TOKEN }} --prebuilt --confirm --prod=false

      - name: Get Vercel Deployment URL
        id: vercel-url
        run: echo "Vercel URL: ${{ steps.deploy.outputs.preview-url }}"

      - name: Add comment with preview URL to PR
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: "Preview deployment is live! You can view it here: ${{ steps.vercel-url.outputs.preview-url }}"
